export const aboutImages = [
  "https://imagewedz.oyoroomscdn.com/medium/photologue/images/santhosh-mahal-kalyana-mandapam-triplicane-chennai.jpg",
  "https://t4.ftcdn.net/jpg/07/05/49/89/240_F_705498967_lz8Ze6U7E1oHT8YxXQHYNE2KrLGEjDqZ.jpg",
  "https://t3.ftcdn.net/jpg/06/94/13/56/240_F_694135600_KC48g8biAols8FtLttq7d53xeSHvXgwd.jpg",
];


export const servicesData = [
    {
        id: "01",
        name: "సంబంధం",
        img: "https://i.pinimg.com/736x/98/39/52/983952b39f50d4414a2edb19f61501ac.jpg",
        description: [
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab."
        ]
    },
    {
        id: "02",
        name: " కానుక",
        img: "https://i.pinimg.com/736x/98/39/52/983952b39f50d4414a2edb19f61501ac.jpg",
        description: [
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab."
        ]
    },
    {
        id: "03",
        name: "Magni Dolores",
        img: "https://i.pinimg.com/736x/98/39/52/983952b39f50d4414a2edb19f61501ac.jpg",
        description: [
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab."
        ]
    },
    {
        id: "04",
        name: "Nemo Enim",
        img: "https://i.pinimg.com/736x/98/39/52/983952b39f50d4414a2edb19f61501ac.jpg",
        description: [
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. At aspernatur odit ab.",
        ]
    },

] 



export const galleryImages = {
  All: [
    "https://t4.ftcdn.net/jpg/08/86/12/63/240_F_886126391_zRYK718Nh1oxPo2ycGv66yQag8jUmmoN.jpg",
    "https://kapukalyanavedika.com/assets/img/WhatsApp%20Image%202.jpg",
    "https://kapukalyanavedika.com/assets/img/WhatsApp%20Image%201.jpg",
    "https://kapukalyanavedika.com/assets/img/WhatsApp%20Image%2015.jpg",
    "https://i.pinimg.com/736x/a9/9c/c2/a99cc2212ec6d00deefe97d3c22edb12.jpg",
    "https://cdn-ilbmfjf.nitrocdn.com/gQtAvEqQsEkcApHLZVxAKgHurqnprTSZ/assets/images/optimized/rev-eadc775/digiartphotography.com/wp-content/uploads/pre-wedding-couple-photoshoot-gandipet-hyderabad-digiart-photography-683x1024.jpg",
    "https://thumbs.dreamstime.com/b/very-happy-indian-couple-their-wedding-day-22337930.jpg",

  ],
  Traditional: [
    "https://t4.ftcdn.net/jpg/08/86/12/63/240_F_886126391_zRYK718Nh1oxPo2ycGv66yQag8jUmmoN.jpg",
    "https://kapukalyanavedika.com/assets/img/WhatsApp%20Image%202.jpg",
    "https://kapukalyanavedika.com/assets/img/WhatsApp%20Image%201.jpg",
    "https://kapukalyanavedika.com/assets/img/WhatsApp%20Image%2015.jpg"

  ],
  Artistic: [
    "https://i.pinimg.com/736x/a9/9c/c2/a99cc2212ec6d00deefe97d3c22edb12.jpg",
    "https://cdn-ilbmfjf.nitrocdn.com/gQtAvEqQsEkcApHLZVxAKgHurqnprTSZ/assets/images/optimized/rev-eadc775/digiartphotography.com/wp-content/uploads/pre-wedding-couple-photoshoot-gandipet-hyderabad-digiart-photography-683x1024.jpg",
    "https://cdn0.weddingwire.in/article/5819/original/1280/jpg/79185-pre-wedding-shoot-poses-dreambox-creations-pre-wedding-photo-shoot-pose-in-the-meadows.jpeg",
    "https://images.squarespace-cdn.com/content/v1/5585edeae4b042906e0cfd77/1659007194710-LEV16PHIWGRTGVZQM0XF/AB1_1445.jpg?format=1000w"
  ],
  Natural: [
    "https://i.pinimg.com/736x/57/dc/4c/57dc4c8c5656c97404a4443ca5b7209f.jpg",
    "https://i.pinimg.com/736x/11/5c/12/115c12ef9ca0f80bfad5a37aa4ed2826.jpg",
    "https://i.pinimg.com/736x/fd/26/a4/fd26a42294c2d5d6a27d8f307f9db28d.jpg",
    "https://i.pinimg.com/736x/57/dc/4c/57dc4c8c5656c97404a4443ca5b7209f.jpg",

  ],
  Commercial: [
   "https://i.pinimg.com/736x/a9/9c/c2/a99cc2212ec6d00deefe97d3c22edb12.jpg",
    "https://cdn-ilbmfjf.nitrocdn.com/gQtAvEqQsEkcApHLZVxAKgHurqnprTSZ/assets/images/optimized/rev-eadc775/digiartphotography.com/wp-content/uploads/pre-wedding-couple-photoshoot-gandipet-hyderabad-digiart-photography-683x1024.jpg",
    "https://cdn0.weddingwire.in/article/5819/original/1280/jpg/79185-pre-wedding-shoot-poses-dreambox-creations-pre-wedding-photo-shoot-pose-in-the-meadows.jpeg",
    "https://images.squarespace-cdn.com/content/v1/5585edeae4b042906e0cfd77/1659007194710-LEV16PHIWGRTGVZQM0XF/AB1_1445.jpg?format=1000w"
  ],
};



export const contactList = [
  {
    icon: "fa-solid fa-location-dot",
    name: "address",
    description: "#503, 5th Floor, Plot No.57, Sai Balaji Arcade,Road No.4, Ayyappa Society, Madhapur, HYDERABAD - 500081. India"
  },{
    icon: "fa-solid fa-phone-volume",
    name: "call",
    description: "9392504567"
  },{
    icon: "fa-solid fa-envelope",
    name: "email",
    description: "ysrysrysr@gmail.com"
  },{
    icon: "fa-brands fa-instagram",
    name: "instagram",
    description: "srinu"
  }
]
